package corendonlms.view.panels;

import corendonlms.connectivity.QueryHelper;
import corendonlms.main.CorendonLMS;
import corendonlms.main.util.MiscUtil;
import corendonlms.main.util.StringUtil;
import corendonlms.model.ActionLog;
import corendonlms.model.ILoggable;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Emile Pels
 */
public class RegisterCustomer
        extends javax.swing.JPanel implements ActionListener, ILoggable
{

    /**
     * Creates new form RegisterCustomer
     */
    public RegisterCustomer()
    {
        initComponents();

        setBackground(CorendonLMS.DEFAULT_BACKCOLOR);

        jLabel1.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel2.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel3.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel4.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel5.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel6.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel7.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        invalidLabel.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        invalidLabel.setVisible(false);

        cancelButton.addActionListener(this);
        registerButton.addActionListener(this);

        addTextChangedListener();
    }

    /**
     * Checks whether all required fields are filled out
     *
     * @return Boolean indicating whether all required fields are filled out
     */
    private boolean isCompleteInput()
    {
        return !StringUtil.isStringNullOrWhiteSpace(phoneNumberField.getText())
                && !StringUtil.isStringNullOrWhiteSpace(addressField.getText())
                && !StringUtil.isStringNullOrWhiteSpace(surnameField.getText());
    }
    
    private void addTextChangedListener()
    {
        emailAddressField.getDocument().addDocumentListener(new DocumentListener()
        {

            @Override
            public void insertUpdate(DocumentEvent de) { checkValidity(); }

            @Override
            public void removeUpdate(DocumentEvent de) { checkValidity(); }

            @Override
            public void changedUpdate(DocumentEvent de) { checkValidity(); }

            private void checkValidity()
            {
                String input = emailAddressField.getText();
                invalidLabel.setVisible(!StringUtil.isValidEmailAddress(input));
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent evt)
    {
        Object source = evt.getSource();

        if (source == cancelButton)
        {
            CorendonLMS.MAIN_PANEL.displayPanel(new Hub());
        } else if (source == registerButton)
        {
            if (isCompleteInput())
            {
                boolean success = false;
                String fullName = String.format("%s %s",
                        firstNameField.getText(), surnameField.getText());

                try
                {
                    success = QueryHelper.registerCustomer(fullName,
                            addressField.getText(),
                            emailAddressField.getText(),
                            phoneNumberField.getText());
                } catch (IllegalArgumentException ex)
                {
                    MiscUtil.showMessage("Could not register customer:\n"
                            + ex.getMessage());
                }

                if (success)
                {
                    log(String.format("Registered customer (%s)", fullName));
                }

                MiscUtil.showMessage(String.format("The customer's registration"
                        + " was %ssuccesful!", (success ? "" : "not ")));
            } else
            {
                MiscUtil.showMessage("Not all required fields are filled out.");
            }
        }
    }

    @Override
    public void log(String message)
    {
        QueryHelper.registerLog(new ActionLog(CorendonLMS.currentUser, message));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailAddressField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        invalidLabel = new javax.swing.JLabel();

        jLabel1.setText("First name");

        jLabel2.setText("Surname (*)");

        jLabel3.setText("Primary address line (*)");

        jLabel4.setText("E-mail address");

        jLabel5.setText("Phone number (*)");

        cancelButton.setText("Cancel");

        registerButton.setText("Register");

        jLabel6.setText("* Required fields");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("Please verify the phone number's validity, as this is the preferred way of contact");

        invalidLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        invalidLabel.setText("INVALID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invalidLabel))
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameField)
                            .addComponent(surnameField)
                            .addComponent(phoneNumberField)
                            .addComponent(emailAddressField)
                            .addComponent(addressField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(invalidLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(registerButton)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailAddressField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel invalidLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField surnameField;
    // End of variables declaration//GEN-END:variables
}
