/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corendonlms.view.panels;

import corendonlms.connectivity.DbManager;
import corendonlms.connectivity.QueryHelper;
import corendonlms.main.CorendonLMS;
import corendonlms.main.util.MiscUtil;
import corendonlms.main.util.StringUtil;
import corendonlms.model.ActionLog;
import corendonlms.model.DatabaseTables;
import corendonlms.model.ILoggable;
import corendonlms.model.LuggageSizes;
import corendonlms.view.panels.Search.SearchModes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 *
 * @author Emile Pels
 */
public class RegisterLuggage extends JPanel implements ActionListener, ILoggable
{

    /**
     * Creates new form RegisterLuggage
     */
    public RegisterLuggage()
    {
        initComponents();

        setBackground(CorendonLMS.DEFAULT_BACKCOLOR);

        jLabel1.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel2.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel3.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel4.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel5.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel6.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel7.setForeground(CorendonLMS.DEFAULT_FORECOLOR);

        //TODO: add combobox items
        cancelButton.addActionListener(this);
        registerButton.addActionListener(this);
        searchButton.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent evt)
    {
        Object source = evt.getSource();

        if (source == cancelButton)
        {
            CorendonLMS.MAIN_PANEL.displayPanel(new Hub());
        } else if (source == searchButton)
        {
            CorendonLMS.MAIN_PANEL.displayPanel(
                    new Search(SearchModes.CUSTOMERS));
        } else if (source == registerButton)
        {
            boolean success = false;

            String customerId = customerIdField.getText();
            String brandName = brandField.getText();

            if (!StringUtil.isStringNullOrWhiteSpace(brandName)
                    && QueryHelper.isCustomerIdRegistered(customerId))
            {
                try
                {
                    success = QueryHelper.registerLuggage(colorField.getText(),
                            patternField.getText(), brandName,
                            customerId, weightField.getText(),
                            (LuggageSizes) sizeComboBox.getSelectedItem());
                } catch (IllegalArgumentException ex)
                {
                    MiscUtil.showMessage("Could not register customer:\n"
                            + ex.getMessage());
                }
                
                if (success)
                {
                    String luggageId = DbManager.getLastEntry(
                                    DatabaseTables.LUGGAGE, "luggage_id");
                    
                    log(String.format("Registered luggage. Customer ID: %s"
                            + ", Luggage ID: %s", customerId, luggageId));
                    
                    MiscUtil.showMessage(String.format("Succesfully registered"
                            + " luggage for customer %s.\nThe new luggage's ID"
                            + " is %s.", customerId, luggageId));
                } else
                {
                    MiscUtil.showMessage("There was an error registering the"
                            + " luggage. No changes have been made.");
                }
            } else
            {
                MiscUtil.showMessage("Could not register customer.\nYou did"
                        + "not enter a brand name, or the customer ID is invalid.");
            }
        }
    }

    @Override
    public void log(String message)
    {
        QueryHelper.registerLog(new ActionLog(CorendonLMS.currentUser, message));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        searchButton = new javax.swing.JButton();
        customerIdField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        brandField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        weightField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        colorField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        patternField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sizeComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        searchButton.setText("Search customer ID");

        jLabel1.setText("Customer ID (*)");

        jLabel2.setText("Brand name (*)");

        jLabel3.setText("Weight");

        jLabel4.setText("Color");

        jLabel5.setText("Pattern");

        sizeComboBox.setModel(new DefaultComboBoxModel(LuggageSizes.values()));

        jLabel6.setText("Size");

        registerButton.setText("Register");

        cancelButton.setText("Cancel");

        jLabel7.setText("* Required fields");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sizeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patternField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brandField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(customerIdField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patternField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(cancelButton)
                    .addComponent(jLabel7))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField colorField;
    private javax.swing.JTextField customerIdField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField patternField;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox sizeComboBox;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
