package corendonlms.view.panels;

import corendonlms.connectivity.QueryHelper;
import corendonlms.main.CorendonLMS;
import corendonlms.main.util.MiscUtil;
import corendonlms.main.util.StringUtil;
import corendonlms.model.ActionLog;
import corendonlms.model.DatabaseTables;
import corendonlms.model.ILoggable;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 *
 * @author Emile
 */
public class Search extends JPanel implements ActionListener, ILoggable
{

    public enum SearchModes
    {

        CUSTOMERS, LUGGAGE
    };

    private SearchModes searchMode;
    
    /**
     * Creates new form SearchCustomers
     *
     * @param searchMode Search mode to use for this dialog
     */
    public Search(SearchModes searchMode)
    {
        this.searchMode = searchMode;
        
        initComponents();

        int width = getWidth(), height = getHeight();

        setMinimumSize(getSize());
        setMaximumSize(new Dimension(width * 2, height));

        setBackground(CorendonLMS.DEFAULT_BACKCOLOR);
        jLabel1.setForeground(CorendonLMS.DEFAULT_FORECOLOR);
        jLabel2.setForeground(CorendonLMS.DEFAULT_FORECOLOR);

        String[] fields = (searchMode == SearchModes.CUSTOMERS
                ? DatabaseTables.CUSTOMERS
                : DatabaseTables.LUGGAGE).getColumns();

        fieldComboBox.setModel(new DefaultComboBoxModel(fields));

        backButton.addActionListener(this);
        searchButton.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent evt)
    {
        Object source = evt.getSource();

        if (source == backButton)
        {
            CorendonLMS.MAIN_PANEL.displayPanel(new Hub());
        } else if (source == searchButton)
        {
            String query = queryTextField.getText();
            String column = fieldComboBox.getSelectedItem().toString();

            if (StringUtil.isStringNullOrWhiteSpace(query))
            {
                MiscUtil.showMessage("The search query can not be empty.");
                return;
            }

            log(String.format("Searched %s[%s] for \"%s\"", 
                    searchMode, column, query));
            throw new UnsupportedOperationException("Not supported yet.");
        }
    }

    @Override
    public void log(String message)
    {
        QueryHelper.registerLog(new ActionLog(CorendonLMS.currentUser, message));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        fieldComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        queryTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        fieldComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Search field");

        jLabel2.setText("Search query");

        searchButton.setText("Search");

        backButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(queryTextField)
                    .addComponent(fieldComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(backButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox fieldComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField queryTextField;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
